spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:nutrion}?options=-c%20timezone=UTC
spring.datasource.username=${DB_USERNAME:appuser}
spring.datasource.password=${DB_PASSWORD:apppass}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway migration settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:nutrion}?options=-c%20timezone=UTC
spring.flyway.user=${DB_USERNAME:appuser}
spring.flyway.password=${DB_PASSWORD:apppass}

# Signer key (HMAC - SHA)
jwt.signerKey=${JWT_SIGNER_KEY:5p7Q9zR2xW4vB8nM1kL6jH3gD0sF9aC2eY4uI1oP7tR5eW3qZ2xS8cM4vN1b0A9}